// Turn ADRs + onboarding into committable Markdown artifacts (PRD §P3, §15.1 export).

import type { ADR, RepoProfileLite } from '../types';

export function adrToMarkdown(adr: ADR): string {
  const alts = adr.alternatives.length
    ? adr.alternatives.map((a) => `- **${a.option}** — ${a.whyRejected}`).join('\n')
    : '_None recorded._';
  const cons = adr.consequences.length ? adr.consequences.map((c) => `- ${c}`).join('\n') : '_None recorded._';
  const evidence = adr.evidence.map((e) => `- \`${e.type}\` ${e.ref} — ${e.note}`).join('\n');

  return `# ${adr.id}: ${adr.title}

**Status:** Inferred — Confidence: ${cap(adr.confidence)}
**Category:** ${adr.category}

## Context
${adr.context}

## Decision
${adr.decision}

## Rationale
${adr.rationale}

## Alternatives Considered
${alts}

## Consequences
${cons}

## Evidence
${evidence}
`;
}

export function bundleMarkdown(profile: RepoProfileLite, adrs: ADR[], onboarding: string | null): string {
  const header = `# ArchDecision — ${profile.owner}/${profile.repo}

> Generated by ArchDecision. ADRs are **inferred** from the codebase and grounded in the
> evidence listed under each record. Treat them as a draft to confirm, not ground truth.

- Repository: https://github.com/${profile.owner}/${profile.repo}
- Commit analyzed: \`${profile.sha.slice(0, 10)}\`
- Primary language: ${profile.primaryLanguage || 'unknown'}

---
`;
  const adrSection = adrs.map(adrToMarkdown).join('\n\n---\n\n');
  const onboardingSection = onboarding ? `\n\n---\n\n# Onboarding Guide\n\n${onboarding}` : '';
  return `${header}\n${adrSection}${onboardingSection}\n`;
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
